/**
 * Source-owned product language for the Agents workspace. Runtime messages,
 * agent names, project names, and paths intentionally stay in their source
 * data and are never mirrored here.
 */
export const AGENT_COPY = {
  page: {
    title: "Agent operations",
    filterAll: "All projects",
    filterProject: (name: string) => `Project: ${name}`,
  },
  dashboard: {
    title: "Agent operations",
    scopeAll: "Recorded lifecycle data across all projects",
    scopeProject: "Recorded lifecycle data for the selected project",
    definitions: "Definitions",
    currentOccupancy: "Current occupancy",
    trackedWork: "Tracked work",
    lifecycleTime: "lifecycle time",
    unresolvedSources: "Unresolved sources",
    codexReady: "Codex-ready",
    external: "external",
    disabled: "disabled",
    lanternwatch: "LanternWatch",
    sameName: "Same-name enabled Codex definitions",
    workload: "Recorded agent workload",
    workloadDescription: "Bar length is recorded active time. Supporting values show run count and current instances.",
    noWorkload: "No recorded active windows for this scope yet.",
    runs: (count: number) => `${count} run${count === 1 ? "" : "s"}`,
    activeInstances: (count: number) => `${count} active instance${count === 1 ? "" : "s"}`,
    statusBreakdown: "Run-status context",
    statusDescription: "Run status across the selected scope. This is operational context, not an individual-agent success rate.",
    noRunStatus: "No recorded runs for this scope yet.",
    completed: "Completed",
    interrupted: "Interrupted",
    active: "Active",
    stalled: "Stalled",
    occupancy: "Live occupancy",
    occupancyDescription: "Current snapshot of queued and working agents; it is not a historical concurrency chart.",
    noOccupancy: "No queued or working agents in the current snapshot.",
    queued: "Queued",
    working: "Working",
    project: "Project",
    elapsed: "Elapsed",
    tokens: "Tokens",
    tokenNotReported: "Not reported",
    tokenPartialCoverage: (reported: number, total: number) => `Partial: ${reported} of ${total} reported`,
    tokenCoverage: (reported: number) => `${reported} reported`,
  },
  catalog: {
    title: "Agent roster",
    noScan: "No scan saved yet",
    lastScan: (moment: string) => `Last scan ${moment}`,
    refresh: "Refresh agents",
    settings: "Settings",
    register: "Register TOML",
    create: "Create agent",
    workspaceSources: "Workspace sources",
    manualNotice: "Manual mode never scans by itself. Refresh agents when you want a new snapshot. Resolve starts with Add tag selected.",
    empty: "No saved scan yet. Refresh agents, select Automatic one-time scan, create an agent, or register an existing local TOML.",
    trackedTime: "Tracked time",
    activeNow: "Active now",
    lastActivity: "Last activity",
    runCount: "Runs",
    none: "None",
    remove: "Remove",
    manage: "Manage",
    sourceAndTags: "Source and tags",
    definition: "Definition",
    workspaceDefinition: "Workspace definition",
    noWorkspaceDefinition: "No workspace definition",
    sourcePath: "Source path",
    copyDestinationLabel: "Copy destination",
    detailSeparator: " / ",
    registeredPaths: "Registered workspace paths",
    importedSnapshots: "Imported workspace snapshots",
    noRegisteredPaths: "No workspace paths are registered for manual scans.",
    noImportedSnapshots: "No read-only workspace snapshots are saved.",
    status: {
      working: "Working",
      disabled: "Disabled",
      unresolved: "Source unresolved",
      idle: "Idle",
    },
    group: {
      global: "Global",
      lanternwatch: "LanternWatch",
      workspace: "Workspace",
      "imported-workspace": "Imported workspace",
      external: "External",
    },
    copyDestination: {
      global: "Copy destination: global Codex agents",
      lanternwatch: "Copy destination: managed by LanternWatch",
      workspace: "Copy destination: registered workspace Codex agents",
      external: "Copy destination: choose global or registered workspace",
    },
  },
  modal: {
    close: "Close",
    cancel: "Cancel",
    createTitle: "Create agent",
    destination: "Destination",
    globalAgents: "Global Codex agents",
    workspaceAgents: "Workspace Codex agents",
    workspace: "Workspace",
    name: "Name",
    namePlaceholder: "release-helper",
    description: "Description",
    instructions: "Developer instructions",
    customTags: "Custom tags",
    tagsPlaceholder: "release, trusted",
    create: "Create agent",
    registerTitle: "Register existing TOML",
    registerNote: "Register any valid local agent TOML to track it here. Codex cannot use an external definition until you add a copy to a Codex global or workspace folder.",
    path: "Local TOML path",
    pathPlaceholder: "D:\\Agents\\release-helper.toml",
    register: "Register agent",
    importNote: "LanternWatch copies this TOML and keeps the external original unchanged. The registered external entry is removed after a successful copy to avoid duplicate attribution.",
    addToCodex: "Add to Codex",
    settingsTitle: "Catalog settings",
    workspaceSourcesTitle: "Workspace sources",
    manualWorkspace: "Register a workspace path",
    manualWorkspaceNote: "Register a workspace folder so LanternWatch can include its .codex/agents folder when you explicitly refresh agents. Registration never starts a watcher or background scan.",
    workspacePath: "Workspace folder path",
    workspacePathPlaceholder: "D:\\Work\\example-workspace",
    registerWorkspace: "Register workspace",
    unregisterWorkspace: "Remove registration",
    snapshotWorkspace: "Import a one-time workspace snapshot",
    snapshotWorkspaceNote: "Choose a workspace folder to capture its current .codex/agents definitions as a read-only, one-time browser-folder snapshot. Re-importing the same folder replaces this saved snapshot; it does not watch the folder.",
    importSnapshot: "Import snapshot",
    reimportSnapshot: "Re-import snapshot",
    removeSnapshot: "Remove snapshot",
    snapshotDetails: (count: number, importedAt: string) => `${count} definition${count === 1 ? "" : "s"} - Imported ${importedAt}`,
    snapshotRemovalNote: "Removing a snapshot deletes only LanternWatch-managed snapshot data. It never deletes the workspace folder or copied Codex agents.",
    discovery: "Discovery",
    manual: "Manual - refresh only",
    automaticOnce: "Automatic - scan once now",
    settingsNote: "Automatic scans once when you save this setting. LanternWatch never watches folders, polls for files, or scans again in the background. Same-name sources are handled from each duplicate card, where Add tag is selected by default.",
    saveSettings: "Save settings",
    manage: (name: string) => `Manage ${name}`,
    enabled: "Enabled",
    disabled: "Disabled",
    saveTags: "Save tags",
    rename: "Rename agent",
    turnOff: "Turn off",
    turnOn: "Turn on",
    resolve: (name: string) => `Resolve ${name} sources`,
    collisionNote: "LanternWatch found enabled Codex definitions with the same name. Select a managed definition to add a tag, rename it, or disable it.",
    duplicateDefinitions: (name: string) => `Duplicate ${name} definitions`,
    canChange: "Can change",
    definitionToResolve: "Definition to resolve",
    noManagedDefinition: "This duplicate contains only protected source copies.",
    chooseResolution: "Choose how LanternWatch should handle this duplicate",
    addTag: "Add tag",
    addTagDescription: "Recommended default. Adds the local duplicate-source tag to identify this workspace source. The same-name warning stays because tags do not change which source Codex selects.",
    renameDescription: "Renames only the selected definition and its TOML filename. This can clear the duplicate warning.",
    newName: "New agent name",
    disable: "Disable",
    disableDescription: "Moves only the selected definition to LanternWatch's recoverable disabled-agent store. This can clear the duplicate warning.",
    resolving: "Resolving...",
    disableDefinition: "Disable agent",
    renameDefinition: "Rename agent",
  },
  protection: {
    snapshot: "Read-only snapshot",
    external: "External copy only",
  },
  collision: {
    title: "Same-name Codex definitions found.",
    editable: "Add a tag to identify sources in LanternWatch, or rename/disable a managed definition to remove the ambiguity. Tags keep both entries visible but activity remains unresolved.",
    protected: "This duplicate has no managed definition that LanternWatch can change.",
    resolve: "Resolve in LanternWatch",
    guidance: "View resolution guidance",
  },
  errors: {
    update: "Agent catalog update failed.",
  },
} as const;
